### ISSUE TITLE
Not working (error in comment)

### ISSUE THREAD

**Issue by MagePsycho** [vseager/magento2-snowdog-menu-luma#1]
I am getting this error
> 1 exception(s):
> Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in vendor/vseager/magento2-snowdog-menu-luma/Plugin/Menu.php on line 102

**Comment by vy-shmal** [comment]
Hi, if you still got this issue change the Identifier of your menu in Content -> Menus -> Your Menu to 

> "main"

Like that 
![Screenshot from 2022-04-18 17-07-46](https://user-images.githubusercontent.com/14836183/163820440-8d85b8db-3748-4539-a9be-ff06a9dd5ee0.png)

**Comment by vseager** [comment]
@MagePsycho sorry for the slow response. @vy-shmal's response is correct, just set the "Identifier" to "main".
